### ISSUE TITLE
Crash on Genymotion emulator with GApps

### ISSUE THREAD

**Issue by dsdebastiani** [inloop/easygcm#28]
I'm trying to run my application in the Geenymotion emulator. I have installed the Google Play Services (part of Google Apps)

The problem is, when the app runs, the class *GcmHelper.java* trhow an exception:
```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
       at android.app.ContextImpl.startService(ContextImpl.java:1161)
       at android.content.ContextWrapper.startService(ContextWrapper.java:383)
       at com.google.android.gms.gcm.GoogleCloudMessaging.e()
       at com.google.android.gms.gcm.GoogleCloudMessaging.register()
       at eu.inloop.easygcm.GcmHelper$1.doInBackground(GcmHelper.java:189)
       at eu.inloop.easygcm.GcmHelper$1.doInBackground(GcmHelper.java:180)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
```
This is a problem with Play Services or in the gcmeasy lib? Someone had this problem?

**Comment by dsdebastiani** [comment]
The problem seems be with the Android System image for Genymotion. I have been tried with Android 4.1 - API16, but I had the crash above. With Android 5.0 - API21 I didn't have problem. My app works fine. I will try with others system versions to check the compatibility.

If someone had same problem, try this: http://inthecheesefactory.com/blog/how-to-install-google-services-on-genymotion/en

**Comment by DanielNovak** [comment]
I am closing this issue - please open a new one if you can replicate it. Thanks for reporting.
